INSERT INTO credits (ACCOUNT_ID, USER_ID, ACCOUNT_TYPE, BALANCE, STATUS) VALUES ('acc1', 'user1', 'CREDIT', 123.5, 'OPEN');
INSERT INTO credits (ACCOUNT_ID, USER_ID, ACCOUNT_TYPE, BALANCE, STATUS) VALUES ('acc2', 'user1', 'CREDIT', 256.7, 'OPEN');
INSERT INTO credits (ACCOUNT_ID, USER_ID, ACCOUNT_TYPE, BALANCE, STATUS) VALUES ('acc3', 'user2', 'CREDIT', 440.8, 'OPEN');
INSERT INTO credits (ACCOUNT_ID, USER_ID, ACCOUNT_TYPE, BALANCE, STATUS) VALUES ('acc4', 'user2', 'CREDIT', 741.6, 'OPEN');
INSERT INTO credits (ACCOUNT_ID, USER_ID, ACCOUNT_TYPE, BALANCE, STATUS) VALUES ('acc5', 'user1', 'CREDIT', 258.2, 'OPEN');
